name: Deployment pipeline

on:
  push:
    branches:
      - main
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style by prettier
        run: npm run format
      - name: test
        run: npm test
        env: 
          TEST_MONGODB_URI:
            ${{ secrets.TEST_MONGODB_URI }}
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3003
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')  }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  discord_message:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
           severity: info
           details: Deploy Succeeded!
           webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deploy Failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: error
            etails: Deploy Failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}